name: "check install hash"
on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        repo:
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
    runs-on: "ubuntu-latest"
    steps:
      - uses: "DeterminateSystems/nix-installer-action@main"
      - run: cat /etc/nix/nix.conf
      - run: cat /etc/nix/nix.conf | grep -v access-tokens | sha256sum -
